export const ACTION_TYPES = {
  EMAIL_VALUE_HANDLE: "EMAIL_VALUE_HANDLE",
  EMAIL_IS_VALID: "EMAIL_IS_VALID",
  PASSWORD_VALUE_HANDLE: "PASSWORD_VALUE_HANDLE",
  PASSWORD_IS_VALID: "PASSWORD_IS_VALID",
};
